### ISSUE TITLE
working prototype for using mozilla donwload manager

### ISSUE THREAD

**Issue by ghost** [pzirnik/SFSCextractor#1]
Hi Tami,

I did some progress on using the firefox download manager from the extension:

1) manifest for extension 
```
{
    "manifest_version": 2,
    "name": "myTestExt",
    "version": "1.0",
    "description": "Blah blah blah",
    "permissions": ["downloads"],
    "background": {
        "scripts": ["mytestdownload.js"]
    },
        "content_scripts": [
        {
            "matches": ["http://192.168.122.58/*"],
            // "js": ["mytestext.js"]
        }
    ]
}
```

2) simple test js (mytestdownload.js) script that downloads test2.file from given url and puts it inside give folder, the folder is created automaticaly if doesn't already exist:

```
browser.downloads.download({url: "http://192.168.122.58/test2.file",
                            saveAs: true,
                            filename: "test_downloads/test2x.file"}
                          )
```
 
We could use a case  number instead of 'test_downloads' . If you think it worth it, then it might make sense to add you JS extension here so I can pull and experiment with the above.

br,
aziz

**Comment by pzirnik** [comment]
The problem is that we have a download URL that does not provide the original filename.
Is it possible to read and modify the "filename" property prior the real download does start ?
If it works to read and modify the filename at this stage, it would be great.
